### ISSUE TITLE
🎉  lineBreakStrategy

### ISSUE THREAD

**Issue by bang9** [bang9/react-native-wrapped-text#2]
네이티브에서 한글에 대한 word wrap 을 지원할 예정입니다. (현재 베타)

https://developer.apple.com/documentation/uikit/nsparagraphstyle/linebreakstrategy?changes=_7

**Comment by Bang9** [comment]
https://github.com/facebook/react-native/pull/31272
 PR이 생성되었습니다!

**Comment by bang9** [comment]
머지되었습니다.
